# Auto update from Guizhan Build is enabled by default.
# Auto update or not.
auto-update: false
# Build station to use.
build-station: "Guizhan" # Expected "Guizhan" or "Blob"

# Do not change this value unless you know what you are doing.
config-version: C_20250224_1

# Do not change this value unless you know what you are doing.
debug: false
